import sqlite3, json, sys

db_path = sys.argv[1] if len(sys.argv) > 1 else '/tmp/db_recreate.db'
conn = sqlite3.connect(db_path)
c = conn.cursor()

row = c.execute("SELECT id, fields FROM _collections WHERE name='cards'").fetchone()
if row:
    cid, fields_json = row
    fields = json.loads(fields_json)
    names = {f['name'] for f in fields}
    if 'id' not in names:
        # Prepend id as the first field (text, required, auto-generated by PB)
        fields.insert(0, {'name': 'id', 'type': 'text', 'required': True, 'options': {}, 'system': True, 'pk': True})
        c.execute("UPDATE _collections SET fields=? WHERE name='cards'", (json.dumps(fields),))
        print('Added id field to cards collection')
    else:
        print('id field already exists')
else:
    print('cards collection not found')

conn.commit()
conn.close()
